workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: Instagram-clone
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/bruh.apk
