workflows:
  my-workflow:
     name: Apk Build
     environment:
      flutter: stable   # Define the channel name or version (e.g., v1.13.4)
      xcode: latest     # Define latest, edge or version (e.g., 11.2)
      cocoapods: 1.9.1  # Define default or version
      node: 12.14.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      npm: 6.13.7       # Define default, latest, next, lts or version
      ndk: r21d         # Define default or revision (e.g., r19c)
      java: 1.8       
     scripts:
      - name: Build Android APK
        script: ./gradlew assembleRelease 
     artifacts:
      - app/build/outputs/bruh.apk
