name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
-steps:
  - name: Set up JDK 1.8
    uses: actions/setup-java@v1
    with:
    java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@2

    - name: Build with Gradle
      run: ./gradlew build
