name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Preparing Android SDK and grant permission for Gradlew command
      run: sudo apt install android-sdk && chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
