name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Generating debug keystore and SHA1 key
      shell: powershell
      run:
          md C:\Users\runneradmin\.android
          keytool -genkey -dname "cn=Abhishek Dubey, ou=DSCBVPPUNE, o=Google, l=Pune, st=Maharashtra, c=IN" -keystore C:\Users\runneradmin\.android\debug.keystore -storepass android -alias AndroidDebugKey -keyalg RSA -keysize 4096 -validity 10000 -v
    - name: Displaying debug.keystore file
      shell: powershell
      run: keytool -list -v -keystore C:\Users\runneradmin\.android\debug.keystore -alias AndroidDebugKey -storepass android -keypass android
